name: Feature Request
description: Suggest a new feature or improvement for ralph
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea so we can evaluate it.

  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: A clear description of the problem or limitation you're facing.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the solution or feature you'd like to see.
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've considered.
      placeholder: Describe alternatives...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or references that might help.
      placeholder: Add any other context here...
    validations:
      required: false
